version: '3.3'

services:
  node:
    container_name: node
    build: ./docker/node/
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    tty: true
  python:
    container_name: python
    build: ./docker/python/
    ports:
      - 5000:5000
    tty: true
    volumes:
      - ./api/:/app
